spring:
  #redis
  redis:
    database: 0
    host:
    port: 6379
    password:
    timeout: 3000ms
    lettuce:
      pool:
        max-idle: 8
        max-active: 8
        max-wait: -1ms
        min-idle: 0